version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "url_shortener_service"
      POSTGRES_PASSWORD: "pqV7EJ8bYJpFDXXJtw66s6JKG4xpZb4v"
      POSTGRES_DB: "url_shortener"
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    restart: always

