version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - ../migrate/20230630113828_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "url_shortener_service"
      POSTGRES_PASSWORD: "pqV7EJ8bYJpFDXXJtw66s6JKG4xpZb4v"
      POSTGRES_DB: "url_shortener"
    networks:
      - urlshortener
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    networks:
      - urlshortener
    restart: always
  app:
    image: "urlshortener:latest"
    ports:
      - "8080:8080"
    networks:
      - urlshortener
    volumes:
      - ../config:/app/deployments/config
    environment:
      CONFIG_NAME: app.dev
networks:
  urlshortener:
    name: urlshortener

