---
log:
  env: dev
  app: url-shortener
  debug: false
  level: 0
database:
  conn:
    debug: false
    host: 'postgres'
    user: 'url_shortener_service'
    password: 'pqV7EJ8bYJpFDXXJtw66s6JKG4xpZb4v'
    port: 5432
    name: 'url_shortener'
    type: 'postgres'
http:
  mode: false
  port: ":8080"
redis:
  addr: 'redis:6379'
bloomFilterNamespace: 'UrlShortenerBF'
serverHost: 'http://localhost:8080'