---
log:
  env: local
  app: url-shortener
  debug: true
  level: 0
database:
  conn:
    debug: true
    host: '127.0.0.1'
    user: 'url_shortener_service'
    password: 'pqV7EJ8bYJpFDXXJtw66s6JKG4xpZb4v'
    port: 5432
    name: 'url_shortener'
    type: 'postgres'
http:
  mode: debug
  port: ":8080"
redis:
  addr: '127.0.0.1:6379'
bloomFilterNamespace: 'UrlShortenerBF'
serverHost: 'http://localhost:8080'
